In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("HousePricePrediction (1).csv")
df

        Id  MSSubClass MSZoning  ...  BsmtFinSF2 TotalBsmtSF SalePrice
0        0          60       RL  ...         0.0       856.0  208500.0
1        1          20       RL  ...         0.0      1262.0  181500.0
2        2          60       RL  ...         0.0       920.0  223500.0
3        3          70       RL  ...         0.0       756.0  140000.0
4        4          60       RL  ...         0.0      1145.0  250000.0
...    ...         ...      ...  ...         ...         ...       ...
2914  2914         160       RM  ...         0.0       546.0       NaN
2915  2915         160       RM  ...         0.0       546.0       NaN
2916  2916          20       RL  ...         0.0      1224.0       NaN
2917  2917          85       RL  ...         0.0       912.0       NaN
2918  2918          60       RL  ...         0.0       996.0       NaN

[2919 rows x 13 columns]

In [4]:
df.shape
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

                Id   MSSubClass  ...  TotalBsmtSF      SalePrice
count  2919.000000  2919.000000  ...  2918.000000    1460.000000
mean   1459.000000    57.137718  ...  1051.777587  180921.195890
std     842.787043    42.517628  ...   440.766258   79442.502883
min       0.000000    20.000000  ...     0.000000   34900.000000
25%     729.500000    20.000000  ...   793.000000  129975.000000
50%    1459.000000    50.000000  ...   989.500000  163000.000000
75%    2188.500000    70.000000  ...  1302.000000  214000.000000
max    2918.000000   190.000000  ...  6110.000000  755000.000000

[8 rows x 9 columns]

In [5]:
# Data processing - Data Cleaning

# Drop Id cause it doesn't contribute in price 
# df.drop(['Id'] , 
#         axis = 1,
#         inplace = True
#         )

# Replacing SalesPrice empty values with mean values 

df['SalePrice'] = df['SalePrice'].fillna(
                  df['SalePrice'].mean()
)

# drop records with null values 
df = df.dropna() 
df.isnull().sum()
df.head()

   Id  MSSubClass MSZoning  ...  BsmtFinSF2 TotalBsmtSF SalePrice
0   0          60       RL  ...         0.0       856.0  208500.0
1   1          20       RL  ...         0.0      1262.0  181500.0
2   2          60       RL  ...         0.0       920.0  223500.0
3   3          70       RL  ...         0.0       756.0  140000.0
4   4          60       RL  ...         0.0      1145.0  250000.0

[5 rows x 13 columns]

In [6]:
#  Data processing - Encoding 

cols = ["MSZoning" , "LotConfig" , "BldgType" , "Exterior1st"]
df = pd.get_dummies(df , columns=cols , drop_first=True)

In [7]:
df.head()
# here colums are droped as meantioned inthe above

   Id  MSSubClass  ...  Exterior1st_Wd Sdng  Exterior1st_WdShing
0   0          60  ...                False                False
1   1          20  ...                False                False
2   2          60  ...                False                False
3   3          70  ...                 True                False
4   4          60  ...                False                False

[5 rows x 35 columns]

In [8]:
# Train test split 

from sklearn.model_selection import train_test_split

X = df.drop(["SalePrice"] , axis=1)
Y = df["SalePrice"]

X_train , X_test , Y_train , Y_test = train_test_split(
    X , Y , test_size=0.2 , random_state=0
)

In [9]:
X_train.head()

        Id  MSSubClass  ...  Exterior1st_Wd Sdng  Exterior1st_WdShing
1453  1453          20  ...                False                False
2021  2021          20  ...                False                False
188    188          90  ...                False                False
1273  1273          80  ...                False                False
1960  1960          20  ...                False                False

[5 rows x 34 columns]

In [10]:
# Train the linear regression model

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train , Y_train)

LinearRegression()

In [14]:


from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error 
import numpy as np

y_pred = model.predict(X_test)

print("R2 Score :" , r2_score(Y_test , y_pred))
print("Mean Absolute Error :" , mean_absolute_error(Y_test , y_pred))
print("Mean Squared Error :" , mean_squared_error(Y_test , y_pred))
print("Mean Absolute Percentage Error :" , mean_absolute_percentage_error(Y_test , y_pred))

R2 Score : 0.3750500172831428
Mean Absolute Error : 30746.80148486167
Mean Squared Error : 1689926129.8857641
Mean Absolute Percentage Error : 0.1863344153134705

In [16]:
# Feature Scaling [ improving baseline performance ]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled , Y_train)

y_pred = model.predict(X_test_scaled)

print("R2 Score" , r2_score(Y_test , y_pred))
print("Mean Abolute Error" , mean_absolute_error(Y_test , y_pred))
print("Mean Squred Error " , np.sqrt(mean_squared_error(Y_test , y_pred)))
print(mean_absolute_percentage_error(Y_test, y_pred))

R2 Score 0.3750500172831337
Mean Abolute Error 30746.80148486184
Mean Squred Error  41108.71111924805
0.1863344153134715